#pragma once

#include <QtWidgets/QMainWindow>
#include "ui_TSS_App.h"
#include "ThemeUtils.h"

/**
 * @class TSS_App
 * @brief Main window for the photo management application.
 *
 * @details
 * Provides the core UI for:
 * - Importing photos
 * - Exporting selected/edited photos
 * - Displaying, navigating, and filtering photo lists
 * - Switching between dark and light application themes
 *
 * @see PhotoTableModel
 * @see PhotoExportDialog
 * @see ThemeUtils
 */
class TSS_App : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief Constructs the main application window.
     * @param parent Optional parent widget.
     */
    TSS_App(QWidget* parent = nullptr);

    /**
     * @brief Destroys the main window.
     */
    ~TSS_App();

private slots:
    /**
     * @brief Opens a dialog to import photos into the application.
     *
     * @see PhotoTableModel::addPhoto()
     */
    void importPhotos();

    /**
     * @brief Opens the export dialog where the user selects export paths.
     *
     * @see PhotoExportDialog
     */
    void exportPhotos();

    /**
     * @brief Toggles between light and dark application themes.
     *
     * @details Uses ThemeUtils to persist and apply theme preference.
     * @see ThemeUtils
     */
    void toggleDarkMode();

protected:
    /**
     * @brief Event filter for handling input field events (e.g., filter boxes).
     *
     * @param obj Target object receiving the event.
     * @param event Event instance.
     * @return True if the event is consumed, false otherwise.
     *
     * @details
     * Used for dynamic filtering or interaction handling in line edit fields
     * within the UI (e.g., filtering photos by tag or name).
     *
     * @see QMainWindow::eventFilter()
     */
    bool eventFilter(QObject* obj, QEvent* event) override;

private:
    /**
     * @brief Updates the pagination indicator in the UI.
     *
     * @details Called whenever page changes, filters apply, or data reloads.
     */
    void updatePageLabel();

    Ui::TSS_AppClass ui;        ///< UI form generated by Qt Designer.
    bool m_darkMode = true;     ///< Current theme mode flag.
    QLabel* m_placeholderLabel = nullptr; ///< Placeholder for empty views.
};
